apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stt-contact-management
  namespace: contact
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: true
      enableHttp2: false
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoints_label_product]
          targetLabel: product
